import type { CollectionConfig } from 'payload'

import { authenticated, publishedOrAuthenticated } from '../access/contentAccess'

export const DailyForecasts: CollectionConfig = {
  slug: 'daily-forecasts',
  labels: { singular: '每日天气预报', plural: '每日天气预报' },
  admin: {
    useAsTitle: 'forecastDate',
    defaultColumns: ['forecastDate', 'headline', '_status', 'updatedAt'],
    description: '按页面分区编写每日预报。保存为草稿不会公开，确认后再发布。',
  },
  access: {
    read: publishedOrAuthenticated,
    create: authenticated,
    update: authenticated,
    delete: authenticated,
  },
  versions: {
    drafts: { autosave: true, schedulePublish: true },
    maxPerDoc: 30,
  },
  fields: [
    {
      name: 'forecastDate',
      label: '预报日期',
      type: 'date',
      required: true,
      unique: true,
      index: true,
      admin: { date: { pickerAppearance: 'dayOnly', displayFormat: 'yyyy年M月d日' } },
    },
    { name: 'headline', label: '当日标题／一句话概述', type: 'text', maxLength: 100 },
    {
      name: 'todayObservation',
      label: '今日深圳天气实况',
      type: 'group',
      fields: [
        {
          name: 'period',
          label: '实况时段',
          type: 'text',
          defaultValue: '昨日20时至今日20时',
          required: true,
          admin: { readOnly: true },
        },
        { name: 'lowTemperature', label: '最低气温（℃）', type: 'number', required: true },
        { name: 'highTemperature', label: '最高气温（℃）', type: 'number', required: true },
        { name: 'averageTemperatureValue', label: '平均温度（℃）', type: 'number', required: true },
        { name: 'temperatureRange', label: '旧版高低温', type: 'text', admin: { hidden: true } },
        { name: 'averageTemperature', label: '旧版平均温度', type: 'text', admin: { hidden: true } },
        { name: 'rainfallAmount', label: '降水量（mm）', type: 'number' },
        { name: 'precipitationLevel', label: '量级', type: 'text', maxLength: 100 },
        { name: 'rainfall', label: '旧版降水量与量级', type: 'text', admin: { hidden: true } },
      ],
    },
    {
      name: 'tomorrowForecast',
      label: '明日南科天气预报',
      type: 'group',
      fields: [
        {
          name: 'period',
          label: '预报时段',
          type: 'text',
          defaultValue: '今日20时至明日20时',
          required: true,
          admin: { readOnly: true },
        },
        { name: 'weather', label: '天气', type: 'text', maxLength: 100 },
        { name: 'lowTemperature', label: '最低气温（℃）', type: 'number', required: true },
        { name: 'highTemperature', label: '最高气温（℃）', type: 'number', required: true },
        { name: 'temperatureRange', label: '旧版气温范围', type: 'text', admin: { hidden: true } },
        { name: 'wind', label: '风向风速', type: 'text', maxLength: 100 },
        { name: 'rainProbability', label: '降水概率', type: 'text', maxLength: 50 },
        { name: 'rainfallAmount', label: '降水量（mm）', type: 'number' },
        { name: 'rainfall', label: '旧版降水量', type: 'text', admin: { hidden: true } },
        {
          name: 'precipitationTimingIntensity',
          label: '可能的降水时段&雨强预报',
          type: 'textarea',
          maxLength: 1000,
        },
      ],
    },
    {
      name: 'threeDayForecast',
      label: '三日南科天气预报',
      type: 'array',
      maxRows: 3,
      admin: { description: '每一天增加一行，最多三行。' },
      fields: [
        { name: 'date', label: '日期', type: 'text', required: true, maxLength: 30 },
        { name: 'weather', label: '天气', type: 'text', required: true, maxLength: 100 },
        { name: 'lowTemperature', label: '最低气温（℃）', type: 'number', required: true },
        { name: 'highTemperature', label: '最高气温（℃）', type: 'number', required: true },
        { name: 'temperatureRange', label: '旧版气温范围', type: 'text', admin: { hidden: true } },
      ],
    },
    { name: 'shenzhenOverview', label: '深圳天气概述', type: 'textarea', maxLength: 5000 },
    { name: 'chinaOverview', label: '国内天气概述', type: 'textarea', maxLength: 10000 },
    {
      name: 'disclaimer',
      label: '声明',
      type: 'textarea',
      defaultValue: '本预报为非官方天气预报，供服务校内师生使用，仅供参考',
      required: true,
      maxLength: 500,
      admin: { readOnly: true },
    },
  ],
}
